[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "gatsby develop"
  port = 8000
  targetPort = 8000
  publish = "public"
  autoLaunch = true 